onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/core_clk
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/resetn
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/regbank_clk
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/regbank_resetn
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_awaddr
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_awprot
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_awvalid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_awready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_wdata
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_wstrb
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_wvalid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_wready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_araddr
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_arprot
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_arvalid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_arready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_rdata
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_rresp
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_rvalid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_rready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_bresp
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_bvalid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/s_axi_bready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_age_req_valid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_age_req_ready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_age_req
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_age_resp_valid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_age_resp
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_fte_req_valid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_fte_req_ready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_fte_req
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_fte_resp_valid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_fte_resp
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_prefetcher_req_valid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_prefetcher_req_ready
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_prefetcher_req
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_prefetcher_resp_valid
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_prefetcher_resp
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/graph_config_node_count_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_start_addr_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_done_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_done_ack_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslot_finished
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_neighbour_count_count_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_node_id_id_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_precision_precision_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_config_make_valid_value_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_neighbour_count_strobe_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_node_id_strobe_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_precision_strobe_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_config_make_valid_strobe_hw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_0_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_1_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_2_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_3_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_4_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_5_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_6_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_7_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_fetch
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_precision_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_precision_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_done_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_done_done
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_done_ack_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_fetch_layer_weights_done_ack_ack
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_start_addr_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/concat_width_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/concat_width_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_done_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/ctrl_start_nodeslot_fetch_done_ack_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/graph_config_node_count_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_valid_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_valid_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_in_features_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_in_features_count
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_out_features_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_out_features_count
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_adjacency_list_address_lsb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_adjacency_list_address_lsb_lsb
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_adjacency_list_address_msb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_adjacency_list_address_msb_msb
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_weights_address_lsb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_weights_address_lsb_lsb
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_weights_address_msb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_weights_address_msb_msb
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_aggregate_enable_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_aggregate_enable_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_node_state_state
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_node_state_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_aggregation_function_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_aggregation_function_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_config_aggregation_wait_count_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_config_aggregation_wait_count_count
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_allocated_fetch_tag_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_allocated_fetch_tag_fetch_tag
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslot_state
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslot_state_n
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/fetch_nb_list_resp_received
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/fetch_scale_factors_resp_received
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/fetch_nbs_resp_received
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/aggregation_done
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/transformation_done
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslots_waiting_nb_list_fetch
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslots_waiting_neighbour_fetch
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslots_waiting_scale_factor_fetch
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslots_waiting_prefetcher
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslots_waiting_aggregation
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nodeslots_waiting_transformation
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/accepting_prefetch_request
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/accepting_aggregation_request
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/accepting_transformation_request
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/aggregation_buffer_population_count
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/prefetcher_arbiter_grant_oh
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/prefetcher_arbiter_grant_bin
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/age_arbiter_grant_bin
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/weights_fetched
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/waiting_weights_fetch_req
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/active_weights_fetch_precision
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/aggregation_buffer_waiting_transformation
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/aggregation_buffer_slots_waiting_transformation
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/aggregation_buffer_precision_arb_bin
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/fte_request_timeout
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_lsb_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_lsb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_msb_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_msb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_scale_factors_address_lsb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_scale_factors_address_lsb_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_scale_factors_address_msb_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/layer_config_scale_factors_address_msb_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_neighbour_count_count
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_node_id_id
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_precision_precision
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_config_make_valid_value
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_neighbour_count_count_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_node_id_id_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_precision_precision_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_config_make_valid_value_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_neighbour_count_strobe_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_node_id_strobe_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_precision_strobe_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/nsb_nodeslot_config_make_valid_strobe_sw
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_0_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_1_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_2_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_3_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_4_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_5_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_6_strobe
add wave -noupdate -group NSB /top_wrapper/top_i/node_scoreboard_i/status_nodeslots_empty_mask_7_strobe
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/core_clk
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/resetn
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arid
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_araddr
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arlen
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arsize
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arburst
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arlock
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arcache
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arprot
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arqos
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arvalid
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_arready
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_rid
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_rdata
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_rresp
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_rlast
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_rvalid
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/read_master_axi_rready
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_neighbour_count_count_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_node_id_id_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_precision_precision_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_config_make_valid_value_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_neighbour_count_strobe_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_node_id_strobe_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_precision_strobe_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_config_make_valid_strobe_hw
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_0_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_1_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_2_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_3_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_4_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_5_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_6_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/status_nodeslots_empty_mask_7_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/graph_config_node_count_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/ctrl_start_nodeslot_fetch_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/ctrl_start_nodeslot_fetch_start_addr_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/ctrl_start_nodeslot_fetch_done_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/ctrl_start_nodeslot_fetch_done_ack_value
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nodeslot_finished
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_req_valid
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_req_ready
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_start_address
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/required_bytes
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_resp_valid
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_resp_last
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_resp_data
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_resp_data_q
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetch_resp_axi_id
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nodeslots_empty_status_mask
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nodeslots_programmed_mask
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nodeslot_free_mask
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/granted_nodeslot_oh
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/granted_nodeslot_bin
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetched_beat_valid
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetched_beat
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/slot_counter
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_neighbour_count_count_hw_n
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_node_id_id_hw_n
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_precision_precision_hw_n
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/nsb_nodeslot_config_make_valid_value_hw_n
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/required_transactions
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/fetched_nodeslots
add wave -noupdate -group NSBPRETCHER /top_wrapper/top_i/nodeslot_prefetcher_i/next_node_id
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {53705094 ps} 0} {{Cursor 2} {1044140000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 430
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {544083750 ps}
bookmark add wave bookmark0 {{17959609 ps} {22111537 ps}} 0
bookmark add wave bookmark1 {{18551117 ps} {18990769 ps}} 0
