name: Verilog Code Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug

jobs:
  verilog-lint:
    runs-on: ubuntu-latest
    container:
      image: alexanderlwhite/ample-image:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Verible Linter
        run: |
          mkdir -p lint_reports
          find . -name "*.sv" -or -name "*.v" | xargs -I {} sh -c 'verible-verilog-lint {} > lint_reports/$(basename {}).lint'

      - name: Upload lint reports
        uses: actions/upload-artifact@v4
        with:
          name: verilog-lint-reports
          path: lint_reports/
